version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.3.27
        environment:
          pipeline_folder: diag_pipelines/
          data_folder: data/
          conda_folder: /opt/conda/
    steps:
      - checkout:
          path: $pipeline_folder
      - run:
          name: Add chanels to conda
          command: |
             conda config --add channels defaults
             conda config --add channels conda-forge
             conda config --add channels bioconda
      - run:
          name: Install fonts and unzip
          command: apt-get install -y fontconfig unzip
      - run:
          name: Install snakemake with conda
          command: conda install snakemake=4.8.0=py36_0
      - run:
          name: Download ParSNP bin
          command: |
             wget -qO- https://github.com/marbl/parsnp/releases/download/v1.2/parsnp-Linux64-v1.2.tar.gz > parsnp.tar.gz
             tar xf parsnp.tar.gz
             mv Parsnp-Linux64-v1.2/parsnp /usr/local/bin/parsnp
             rm -rf Parsnp-Linux64-v1.2/
             rm parsnp.tar.gz 
      - run: 
          name: Create BED cgMLST files
          command: |
             mkdir $data_folder 
             cd $data_folder
             snakemake --snakefile ../${pipeline_folder}/workflows/core_genomes/make_ridom.rules --use-conda --conda-prefix ${conda_folder} core_genomes/cgMLST/Staphylococcus_aureus.bed core_genomes/cgMLST/Mycobacterium_tuberculosis.bed core_genomes/cgMLST/Listeria_monocytogenes.bed core_genomes/cgMLST/Klebsiella_pneumoniae.bed core_genomes/cgMLST/Enterococcus_faecium.bed core_genomes/cgMLST/Acinetobacter_baumannii.bed core_genomes/cgMLST/Legionella_pneumophila.bed core_genomes/cgMLST/Clostridioides_difficile.bed -j 2 
             snakemake --snakefile ../${pipeline_folder}/workflows/core_genomes/make_enterobase.rules --use-conda --conda-prefix ${conda_folder} core_genomes/cgMLST/Salmonella_enterica.bed core_genomes/cgMLST/Escherichia_coli.bed references/538048/genome_gbwithparts.gbwithparts
      - run: 
          name: Create reference for MTB
          command: |
             cd $data_folder
             snakemake --snakefile ../${pipeline_folder}/rules/downloading/adapting_genome_files.rules --use-conda --conda-prefix ${conda_folder} references/538048/genome_gbwithparts.gbk
      - run:
          name: Create resistance DBs for MTB
          command: |
             mkdir -p ${data_folder}/resistance_db/
             cp -R ${pipeline_folder}/data/Mycobacterium_tuberculosis ${data_folder}/resistance_db/
             cd $data_folder
             snakemake --snakefile ../${pipeline_folder}/workflows/check_resistance_databases.rules --use-conda --conda-prefix ${conda_folder} resistance_db/Mycobacterium_tuberculosis/mutations/currated_db_all/correct.bed resistance_db/Mycobacterium_tuberculosis/mutations/level_four_agreement/correct.bed resistance_db/Mycobacterium_tuberculosis/mutations/rgi_annotated_full_2_0_0/correct.bed resistance_db/Mycobacterium_tuberculosis/mutations/mykrobe_annotated/correct.bed resistance_db/Mycobacterium_tuberculosis/mutations/miotto_high_moderate_minimum_confidence_annotated/correct.bed resistance_db/Mycobacterium_tuberculosis/mutations/walker_resistant_annotated/correct.bed -j 2
      - run:
          name: Copy virulence factors S. aureus
          command: |
             mkdir -p ${data_folder}/staph/db/
             cp ${pipeline_folder}/data/staph/db/virulence_factors.tsv ${data_folder}/staph/db/
      - run:
          name: Download MASH sketchs
          command: |
             wget -qO- https://gembox.cbcb.umd.edu/mash/refseq.genomes.k21s1000.msh > $data_folder/references/mash_sketch.msh
      - run:
          name: Download all conda environments
          command: |
             mkdir -p tmp/links
             cd tmp
             cp ../${pipeline_folder}/*.tsv .
             cp ../${pipeline_folder}/config.yaml .
             mkdir -p core_genomes/parsnp/Mycobacterium_tuberculosis/
             echo '' > links/Myco-10_S10_L001_R1.fastq.gz 
             echo '' > links/Myco-10_S10_L001_R2.fastq.gz
             echo '' > core_genomes/parsnp/Mycobacterium_tuberculosis/parsnp.xmfa
             echo '' > ../${data_folder}/references/mash_sketch_human.msh
             ln -s -r ../${data_folder}/references/ references
             ln -s -r ../${data_folder}/core_genomes/cgMLST/ core_genomes/cgMLST
             snakemake --snakefile ../${pipeline_folder}/workflows/full_pipeline.rules --use-conda --create-envs-only --conda-prefix ${conda_folder} --configfile config.yaml quality/multiqc/assembly/multiqc_report.html samples/M10/resistance/mykrobe.tsv typing/freebayes_joint_genotyping/cgMLST/bwa/distances_in_snp_mst_no_st.svg typing/gatk_gvcfs/core_parsnp_538048/bwa/distances_in_snp_mst_no_st.svg typing/gatk_gvcfs/full_genome_M10_assembled_genome/bwa/distances_in_snp_mst_no_st.svg virulence_summary.xlsx typing/mlst/summary.xlsx resistance/rgi_summary.xlsx resistance/mykrobe_summary.xlsx phylogeny/freebayes_joint_genotyping/cgMLST/bwa/phylogeny_no_st.svg phylogeny/gatk_gvcfs/full_genome_538048/bwa/phylogeny_no_st.svg phylogeny/gatk_gvcfs/core_parsnp_538048/bwa/phylogeny_no_st.svg contamination/distances_formated.xlsx -j 4 --config species="Mycobacterium_tuberculosis"
             conda clean --all
             cd ..
             rm -rf tmp
      - run:
          name: Create human genome MASH sketch
          command: |
             source activate ${conda_folder}/envs/618592fe/ 
             efetch -db assembly -id 1493941 -format docsum | xtract -pattern DocumentSummary -element FtpPath_RefSeq | sed "s/\(\/GCF_.*\)/\\1\\1_genomic.fna.gz/" | xargs -I % wget -qO- % | gzip -d > ${data_folder}/references/1493941/genome_fasta.fasta
             source deactivate
             source activate ${conda_folder}/envs/c327f08f/
             mash sketch -o ${data_folder}/references/mash_sketch_human.msh ${data_folder}/references/1493941/genome_fasta.fasta
             source deactivate
             rm -rf ${data_folder}/references/1493941/

  


