version: 2

jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.3.27
        environment:
          pipeline_folder: /home/pipeline_user/src/
          data_folder: /home/pipeline_user/data/
          conda_folder: /home/pipeline_user/conda/
    working_directory:  /home/pipeline_user/
    steps:
      - attach_workspace:
          at: /home/pipeline_user/
      - checkout:
          path: src/
      - run:
          name: Create env file
          command: |
             cat ${pipeline_folder}/envs/*.yml > all_envs.yml
      - restore_cache:
          key: v1-{{ checksum "all_envs.yml" }}
      - run:
          name: Add chanels to conda
          command: |
             conda config --add channels defaults
             conda config --add channels conda-forge
             conda config --add channels bioconda
      - run:
          name: Install fontconfig
          command: apt-get install -y fontconfig
      - run:
          name: Install snakemake, entrez-direct and mash with conda
          command: conda install snakemake=4.8.0=py36_0 mash=2.0=gsl1.16_0 entrez-direct=7.70=pl5.22.0_0 
      - run:
          name: Install all conda envs
          command: snakemake --snakefile ${pipeline_folder}/workflows/download_environments.rules --list | xargs -I % sh -c "snakemake --snakefile ${pipeline_folder}/workflows/download_environments.rules --use-conda  --create-envs-only --conda-prefix ${conda_folder} %"
      - run:
          name: Clean conda envs
          command: conda clean --all --yes
      - run:
          name: Download MASH sketchs
          command: |
             mkdir -p ${data_folder}/references/
             wget -qO- https://gembox.cbcb.umd.edu/mash/refseq.genomes.k21s1000.msh > ${data_folder}/references/mash_sketch.msh
      - run: 
          name: Create BED cgMLST files
          command: |
             cd $data_folder
             snakemake --snakefile ${pipeline_folder}/workflows/core_genomes/make_ridom.rules --use-conda --conda-prefix ${conda_folder} core_genomes/cgMLST/Staphylococcus_aureus.bed core_genomes/cgMLST/Mycobacterium_tuberculosis.bed core_genomes/cgMLST/Listeria_monocytogenes.bed core_genomes/cgMLST/Klebsiella_pneumoniae.bed core_genomes/cgMLST/Enterococcus_faecium.bed core_genomes/cgMLST/Acinetobacter_baumannii.bed core_genomes/cgMLST/Legionella_pneumophila.bed core_genomes/cgMLST/Clostridioides_difficile.bed -j 2 
             snakemake --snakefile ${pipeline_folder}/workflows/core_genomes/make_enterobase.rules --use-conda --conda-prefix ${conda_folder} core_genomes/cgMLST/Salmonella_enterica.bed core_genomes/cgMLST/Escherichia_coli.bed references/538048/genome_gbwithparts.gbwithparts
      - run: 
          name: Create reference for MTB
          command: |
             cd $data_folder
             snakemake --snakefile ${pipeline_folder}/rules/downloading/adapting_genome_files.rules --use-conda --conda-prefix ${conda_folder} references/538048/genome_gbwithparts.gbk
      - run:
          name: Create resistance DBs for MTB
          command: |
             mkdir -p ${data_folder}/resistance_db/
             cp -R ${pipeline_folder}/data/Mycobacterium_tuberculosis ${data_folder}/resistance_db/
             cd $data_folder
             snakemake --snakefile ${pipeline_folder}/workflows/check_resistance_databases.rules --use-conda --conda-prefix ${conda_folder} resistance_db/Mycobacterium_tuberculosis/mutations/currated_db_all/correct.bed resistance_db/Mycobacterium_tuberculosis/mutations/level_four_agreement/correct.bed resistance_db/Mycobacterium_tuberculosis/mutations/rgi_annotated_full_2_0_0/correct.bed resistance_db/Mycobacterium_tuberculosis/mutations/mykrobe_annotated/correct.bed resistance_db/Mycobacterium_tuberculosis/mutations/miotto_high_moderate_minimum_confidence_annotated/correct.bed resistance_db/Mycobacterium_tuberculosis/mutations/walker_resistant_annotated/correct.bed -j 2
      - run:
          name: Copy virulence factors S. aureus
          command: |
             mkdir -p ${data_folder}/virulence_factors_db/Staphylococcus_aureus/
             cp ${pipeline_folder}/data/staph/db/virulence_factors.tsv ${data_folder}/virulence_factors_db/Staphylococcus_aureus/
      - run:
          name: Create human genome MASH sketch
          command: |
             mkdir -p ${data_folder}/references/1493941/
             efetch -db assembly -id 1493941 -format docsum | xtract -pattern DocumentSummary -element FtpPath_RefSeq | sed "s/\(\/GCF_.*\)/\\1\\1_genomic.fna.gz/" | xargs -I % wget -qO- % | gzip -d > ${data_folder}/references/1493941/genome_fasta.fasta
             mash sketch -o ${data_folder}/references/mash_sketch_human.msh ${data_folder}/references/1493941/genome_fasta.fasta
             rm -rf ${data_folder}/references/1493941/
      - run: 
          name: Clean folders 
          command: |
             rm -rf ${data_folder}/logs/
             rm -rf ${data_folder}/.snakemake/
      - run:
          name: Patch mykrobe file
          command: |
             patch ${conda_folder}/*/lib/python3.6/site-packages/mykatlas/typing/typer/presence.py < ${pipeline_folder}/patches/mykrobe.patch
      - run:
          name: Change rights RGI and Mykrobe folders
          command: |     
             chmod -R 777 ${conda_folder}/*/lib/python2.7/site-packages/package/rgi/_db/
             chmod -R 777 ${conda_folder}/*/lib/python3.6/site-packages/mykatlas/
      - save_cache:
          key: v1-{{ checksum "all_envs.yml" }}   
          paths: cache_downloads.txt
      - persist_to_workspace:
          root: /home/pipeline_user/
          paths:
            - data/
            - conda/


  test_MTB_typing:
    docker:
      - image: continuumio/miniconda3:4.3.27
        environment:
          pipeline_folder: /home/pipeline_user/src/
          data_folder: /home/pipeline_user/data/
          conda_folder: /home/pipeline_user/conda/
    working_directory:  /home/pipeline_user/
    steps:
      - attach_workspace:
          at: /home/pipeline_user/
      - checkout:
          path: src/
      - run: export _JAVA_OPTIONS=-Xmx3g
      - run: apt-get install -y fontconfig
      - run:
          name: Add chanels to conda
          command: |
             conda config --add channels defaults
             conda config --add channels conda-forge
             conda config --add channels bioconda
      - run:
          name: Install snakemake and entrez-direct with conda
          command: conda install snakemake=4.8.0=py36_0 entrez-direct=7.70=pl5.22.0_0
      - run:
          name: Download SRA MTB for typing
          command: |
            mkdir -p validation/MTB-typing/
            cd validation/MTB-typing/
            ln -s ${data_folder}/core_genomes/ core_genomes
            ln -s ${data_folder}/references/ references
            esearch -db sra -query "PRJEB12011[BIOPROJECT] AND \"Mycobacterium tuberculosis complex\"[ORGANISM]" | efetch -db sra -format runinfo | sed "s/,/\t/g" | head -n 5 > PRJEB12011_Mycobacterium-tuberculosis.tsv || true
      - run:
          name: Run snakemake analysis
          no_output_timeout: 2h
          command: |
            cd validation/MTB-typing/
            snakemake --snakefile ${pipeline_folder}/workflows/resistance.rules --use-conda --conda-prefix $conda_folder --configfile ${pipeline_folder}/data/validation_datasets/config.yml -j 1 typing/freebayes_joint_genotyping/cgMLST/bwa/distances_in_snp_mst_no_st.svg typing/gatk_gvcfs/cgMLST/bwa/distances_in_snp_mst_no_st.svg phylogeny/freebayes_joint_genotyping/cgMLST/bwa/phylogeny_no_st.svg typing/freebayes_joint_genotyping/cgMLST/bwa/vcfs/SAMEA3697004_-_SAMEA3697005_in_snp.vcf typing/gatk_gvcfs/full_genome_SAMEA3697006_assembled_genome/bwa/distances_in_snp_mst_no_st.svg --config sra_samples="PRJEB12011_Mycobacterium-tuberculosis.tsv" species="Mycobacterium_tuberculosis"

  test_MTB_resistance:
    docker:
      - image: continuumio/miniconda3:4.3.27
        environment:
          pipeline_folder: /home/pipeline_user/src/
          data_folder: /home/pipeline_user/data/
          conda_folder: /home/pipeline_user/conda/
    working_directory:  /home/pipeline_user/
    steps:
      - attach_workspace:
          at: /home/pipeline_user/
      - checkout:
          path: src/
      - run: export _JAVA_OPTIONS=-Xmx3g
      - run:
          name: Add chanels to conda
          command: |
             conda config --add channels defaults
             conda config --add channels conda-forge
             conda config --add channels bioconda
      - run:
          name: Install snakemake and entrez-direct with conda
          command: conda install snakemake=4.8.0=py36_0 entrez-direct=7.70=pl5.22.0_0
      - run:
          name: Download SRA XTR MTB 
          command: |
            mkdir -p validation/MTB-XTR/
            cd validation/MTB-XTR/
            ln -s ${data_folder}/references/ references
            esearch -db sra -query "SRR1158874[ID]" | efetch -db sra -format runinfo | sed "s/,/\t/g" > MTB-XTR.tsv
      - run:
          name: Run snakemake analysis
          no_output_timeout: 2h
          command: |
            cd validation/MTB-XTR/
            snakemake --snakefile ${pipeline_folder}/workflows/resistance.rules --use-conda --conda-prefix $conda_folder --configfile ${pipeline_folder}/data/validation_datasets/config.yml -j 1 resistance/mykrobe_summary.xlsx resistance/rgi_summary.xlsx samples/XTB13-114/resistance/mykrobe_annotated/mutations.vcf samples/XTB13-114/resistance/rgi_annotated_full_2_0_0/mutations.vcf --config sra_samples="MTB-XTR.tsv" species="Mycobacterium_tuberculosis" 


  test_Staph_aureus_resistance:
    docker:
      - image: continuumio/miniconda3:4.3.27
        environment:
          pipeline_folder: /home/pipeline_user/src/
          data_folder: /home/pipeline_user/data/
          conda_folder: /home/pipeline_user/conda/
    working_directory:  /home/pipeline_user/
    steps:
      - attach_workspace:
          at: /home/pipeline_user/
      - checkout:
          path: src/
      - run:
          name: Add chanels to conda
          command: |
             conda config --add channels defaults
             conda config --add channels conda-forge
             conda config --add channels bioconda
      - run:
          name: Install snakemake, rgi and entrez-direct with conda
          command: conda install snakemake=4.8.0=py36_0 entrez-direct=7.70=pl5.22.0_0 
      - run:
          name: Download SRAs 
          command: |
            mkdir -p validation/Staph_aureus_resistance/
            cd alidation/Staph_aureus_resistance/
            ln -s ../../core_genomes/ core_genomes
            ln -s ../../references/ references
            esearch -db sra -query "PRJEB7847[BIOPROJECT] AND \"Staphylococcus aureus\"[ORGANISM]" | efetch -db sra -format runinfo | sed "s/,/\t/g" | head -n 3 > PRJEB7847_Staphylococcus-aureus.tsv' || true
      - run:
          name: Run snakemake analysis
          no_output_timeout: 2h
          command: |
            cd validation/Staph_aureus_resistance/
            snakemake --snakefile ${pipeline_folder}/workflows/resistance.rules --use-conda --conda-prefix $conda_folder --configfile ${pipeline_folder}/data/validation_datasets/config.yml -j 1 all_resistance_summaries --config sra_samples="MTB-XTR.tsv" species="Mycobacterium_tuberculosis" 




workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_MTB_resistance:
          requires:
            - build           
      - test_MTB_typing:
          requires:
            - build           
      - test_Staph_aureus_resistance:
          requires:
            - build           

